TNSR v19.02-1
Updated to upstream version 6.0

diff --git a/tools/frr b/tools/frr
--- a/tools/frr
+++ b/tools/frr
@@ -21,11 +21,13 @@ V_PATH=/var/run/frr
 # Local Daemon selection may be done by using /etc/frr/daemons.
 # See /usr/share/doc/frr/README.Debian.gz for further information.
 # Keep zebra first and do not list watchfrr!
-DAEMONS="zebra bgpd ripd ripngd ospfd ospf6d isisd babeld pimd ldpd nhrpd eigrpd sharpd"
+DAEMONS="zebra bgpd ripd ripngd ospfd ospf6d isisd babeld pimd ldpd nhrpd eigrpd sharpd pbrd staticd bfdd"
 MAX_INSTANCES=5
 RELOAD_SCRIPT=/usr/lib/frr/frr-reload.py
 
-. /lib/lsb/init-functions
+if [ -e /lib/lsb/init-functions ]; then
+    . /lib/lsb/init-functions
+fi
 
 if [ -f /usr/lib/frr/ssd ]; then
     SSD=/usr/lib/frr/ssd
@@ -168,6 +170,22 @@ start()
                `eval echo "$""$1""_options"`
            fi
         fi
+
+	# Start the staticd automatically
+	if [ "$1" = "zebra" ]; then
+	    echo -n "starting staticd since zebra is running"
+	    if ! check_daemon staticd ; then
+		echo -n " (binary does not exist)"
+		return;
+	    fi
+
+	    ${SSD} \
+		--start \
+		--pidfile=`pidfile staticd` \
+		--exec "$D_PATH/staticd" \
+		-- \
+		`eval echo "$"staticd"_options"`
+	fi
 }
 
 # Stop the daemon given in the parameter, printing its name to the terminal.
@@ -187,7 +205,7 @@ stop()
     else
         PIDFILE=`pidfile $inst`
         PID=`cat $PIDFILE 2>/dev/null`
-        ${SSD} --stop --quiet --retry=TERM/30/KILL/5 --oknodo --pidfile "$PIDFILE" --exec "$D_PATH/$1"
+        kill -2 $PID 2>/dev/null
         #
         #       Now we have to wait until $DAEMON has _really_ stopped.
         #
@@ -208,6 +226,11 @@ stop()
         echo -n " $inst"
         rm -f `pidfile $inst`
         rm -f `vtyfile $inst`
+
+	if [ "$1" = "zebra" ]; then
+	    echo -n "Stopping staticd since zebra is running"
+	    stop staticd
+	fi
     fi
 }
 
@@ -550,16 +573,20 @@ case "$1" in
 	  # Additionally if a new protocol is added
 	  # we need to add it here as well as
 	  # in rt_netlink.h( follow the directions! )
-          ip route flush proto 186
-          ip route flush proto 188
           ip route flush proto 4
+          ip route flush proto 11
+          ip route flush proto 42
+          ip route flush proto 186
+          ip route flush proto 187
+          ip route flush proto 188
           ip route flush proto 189
           ip route flush proto 190
-          ip route flush proto 11
-          ip route flush proto 187
-          ip route flush proto 192
-          ip route flush proto 42
           ip route flush proto 191
+          ip route flush proto 192
+          ip route flush proto 193
+          ip route flush proto 194
+          ip route flush proto 195
+	  ip route flush proto 196
        else
          [ -n "$dmn" ] && eval "${dmn/-/_}=0"
          start_watchfrr
@@ -568,7 +595,11 @@ case "$1" in
 
     reload)
        # Just apply the commands that have changed, no restart necessary
-       [ ! -x "$RELOAD_SCRIPT" ] && echo "frr-reload script not available" && exit 0
+       if [ ! -x "$RELOAD_SCRIPT" ]; then
+          echo "Please install frr-pythontools package. Required for reload"
+          exit 0
+       fi
+
        NEW_CONFIG_FILE="${2:-$C_PATH/frr.conf}"
        [ ! -r $NEW_CONFIG_FILE ] && echo "Unable to read new configuration file $NEW_CONFIG_FILE" && exit 1
        echo "Applying only incremental changes to running configuration from frr.conf"
