TNSR v20.08-3

diff --git a/tools/frrcommon.sh.in b/tools/frrcommon.sh.in
--- a/tools/frrcommon.sh.in
+++ b/tools/frrcommon.sh.in
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 #
 # This is a "library" of sorts for use by the other FRR shell scripts.  It
 # has most of the daemon start/stop logic, but expects the following shell
@@ -24,12 +24,13 @@ VTYSH="@vtysh_bin@" # /usr/bin/vtysh
 FRR_USER="@enable_user@" # frr
 FRR_GROUP="@enable_group@" # frr
 FRR_VTY_GROUP="@enable_vty_group@" # frrvty
+FRR_DEFAULT_PROFILE="@DFLT_NAME@" # traditional / datacenter
 
 # ORDER MATTERS FOR $DAEMONS!
 # - keep zebra first
 # - watchfrr does NOT belong in this list
 
-DAEMONS="zebra bgpd ripd ripngd ospfd ospf6d isisd babeld pimd ldpd nhrpd eigrpd sharpd pbrd staticd bfdd fabricd"
+DAEMONS="zebra bgpd ripd ripngd ospfd ospf6d isisd babeld pimd ldpd nhrpd eigrpd sharpd pbrd staticd bfdd fabricd vrrpd"
 RELOAD_SCRIPT="$D_PATH/frr-reload.py"
 
 #
@@ -67,9 +68,9 @@ vtysh_b () {
 daemon_inst() {
 	# note this sets global variables ($dmninst, $daemon, $inst)
 	dmninst="$1"
-	daemon="${dmninst%:*}"
+	daemon="${dmninst%-*}"
 	inst=""
-	[ "$daemon" != "$dmninst" ] && inst="${dmninst#*:}"
+	[ "$daemon" != "$dmninst" ] && inst="${dmninst#*-}"
 }
 
 daemon_list() {
@@ -92,9 +93,12 @@ daemon_list() {
 			enabled="$enabled $daemon"
 			if [ -n "$inst" ]; then
 				debug "$daemon multi-instance $inst"
+				oldifs="${IFS}"
+				IFS="${IFS},"
 				for i in $inst; do
-					enabled="$enabled $daemon:$inst"
+					enabled="$enabled $daemon-$i"
 				done
+				IFS="${oldifs}"
 			fi
 		else
 			debug "$daemon disabled"
@@ -119,7 +123,7 @@ daemon_prep() {
 	inst="$2"
 	[ "$daemon" = "watchfrr" ] && return 0
 	[ -x "$D_PATH/$daemon" ] || {
-		log_failure_msg "cannot start $daemon${inst:+ (instance $inst)}: daemon binary not installed\n"
+		log_failure_msg "cannot start $daemon${inst:+ (instance $inst)}: daemon binary not installed"
 		return 1
 	}
 	[ -r "$C_PATH/frr.conf" ] && return 0
@@ -148,7 +152,7 @@ daemon_start() {
 	instopt="${inst:+-n $inst}"
 	eval args="\$${daemon}_options"
 
-	if eval "$all_wrap $wrap $bin -d $instopt $args"; then
+	if eval "$all_wrap $wrap $bin -d $frr_global_options $instopt $args"; then
 		log_success_msg "Started $dmninst"
 		vtysh_b "$daemon"
 	else
@@ -279,7 +283,7 @@ load_old_config() {
 }
 
 [ -r "$C_PATH/daemons" ] || {
-	log_failure_msg "cannot run $@: $C_PATH/daemons does not exist\n"
+	log_failure_msg "cannot run $@: $C_PATH/daemons does not exist"
 	exit 1
 }
 . "$C_PATH/daemons"
@@ -287,6 +291,25 @@ load_old_config() {
 load_old_config "$C_PATH/daemons.conf"
 load_old_config "/etc/default/frr"
 load_old_config "/etc/sysconfig/frr"
+
+if { declare -p watchfrr_options 2>/dev/null || true; } | grep -q '^declare \-a'; then
+	log_warning_msg "watchfrr_options contains a bash array value." \
+		"The configured value is intentionally ignored since it is likely wrong." \
+		"Please remove or fix the setting."
+	unset watchfrr_options
+fi
+
+if test -z "$frr_profile"; then
+	# try to autodetect config profile
+	if test -d /etc/cumulus; then
+		frr_profile=datacenter
+	# elif test ...; then
+	# -- add your distro/system here
+	elif test -n "$FRR_DEFAULT_PROFILE"; then
+		frr_profile="$FRR_DEFAULT_PROFILE"
+	fi
+fi
+test -n "$frr_profile" && frr_global_options="$frr_global_options -F $frr_profile"
 
 #
 # other defaults and dispatch
